In [4]:
import pandas as pd

In [51]:
import numpy as np

In [39]:
pip install keras 


Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [40]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


1. DATA LOADING

In [52]:
dataset_path = '/Users/hks/Desktop/marketing_sample_for_amazon.csv'

# Load the dataset into a DataFrame
df = pd.read_csv(dataset_path)

# Display the first few rows of the DataFrame to understand its structure
print(df.head())


                            Uniq Id  \
0  4c69b61db1fc16e7013b43fc926e502d   
1  66d49bbed043f5be260fa9f7fbff5957   
2  2c55cae269aebf53838484b0d7dd931a   
3  18018b6bc416dab347b1b7db79994afa   
4  e04b990e95bf73bbe6a3fa09785d7cd0   

                                        Product Name  Brand Name  Asin  \
0  DB Longboards CoreFlex Crossbow 41" Bamboo Fib...         NaN   NaN   
1  Electronic Snap Circuits Mini Kits Classpack, ...         NaN   NaN   
2  3Doodler Create Flexy 3D Printing Filament Ref...         NaN   NaN   
3  Guillow Airplane Design Studio with Travel Cas...         NaN   NaN   
4                   Woodstock- Collage 500 pc Puzzle         NaN   NaN   

                                            Category Upc Ean Code  List Price  \
0  Sports & Outdoors | Outdoor Recreation | Skate...          NaN         NaN   
1  Toys & Games | Learning & Education | Science ...          NaN         NaN   
2          Toys & Games | Arts & Crafts | Craft Kits          NaN         NaN

2. DATA GENERATION

In [54]:
import pandas as pd
import numpy as np

# Generate dummy data
data = {
    'name': ['Product1', 'Product2', 'Product3', 'Product4', 'Product5'],
    'description': [
        'Medicom Neon Genesis Evangelion: Eva Evangelion Unit 01 Shogo-Ki Maf Ex Action Figure',
        'Disneys Alice in Wonderland, "The Hatters Mad" Woven Tapestry Throw Blanket, 48" x 60", Multi Colo...',
        'Delta Children Plastic Toddler Bed, Nickelodeon SpongeBob SquarePants',
        'Kettler Advantage Indoor Table Tennis Bundle: 4 Player Set (4 Rackets/Paddles and 8 Balls)',
        'Rubies Childs Pokemon Deluxe Pikachu Costume, X-Small'
    ],
    'price': [102.53, 35.00, 58.49, 37.97, 29.12],
    'category': ['Toy', 'Home', 'Baby Products', 'Sports', 'Clothing']
}

# Create DataFrame
df = pd.DataFrame(data)
print(df)



       name                                        description   price  \
0  Product1  Medicom Neon Genesis Evangelion: Eva Evangelio...  102.53   
1  Product2  Disneys Alice in Wonderland, "The Hatters Mad"...   35.00   
2  Product3  Delta Children Plastic Toddler Bed, Nickelodeo...   58.49   
3  Product4  Kettler Advantage Indoor Table Tennis Bundle: ...   37.97   
4  Product5  Rubies Childs Pokemon Deluxe Pikachu Costume, ...   29.12   

        category  
0            Toy  
1           Home  
2  Baby Products  
3         Sports  
4       Clothing  


3. DATA PREPROCESSING

In [56]:
pip show tensorflow


Name: tensorflow
Version: 2.16.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/hks/Library/Python/3.9/lib/python/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, libclang, ml-dtypes, numpy, opt-einsum, packaging, protobuf, requests, setuptools, six, tensorboard, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [57]:
pip install --upgrade tensorflow


Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [58]:
from tensorflow.keras.preprocessing.text import Tokenizer


In [59]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Encode categories
label_encoder = LabelEncoder()
df['category_encoded'] = label_encoder.fit_transform(df['category'])

# Tokenize text (name and description)
tokenizer = Tokenizer(num_words=100)
tokenizer.fit_on_texts(df['description'])

# Convert descriptions to sequences
sequences = tokenizer.texts_to_sequences(df['description'])
padded_sequences = pad_sequences(sequences, maxlen=10)  # padding to ensure uniform length

print('Padded Sequences:\n', padded_sequences)
print('Encoded Categories:\n', df['category_encoded'])

Padded Sequences:
 [[ 7  1  8  9 10 11 12 13 14 15]
 [22 23 24 25 26 27  2 28 29 30]
 [ 0  0 31 32 33 34 35 36 37 38]
 [44  3 45 46  3 47 48 49 50 51]
 [ 0  0 52 53 54 55 56 57  2 58]]
Encoded Categories:
 0    4
1    2
2    0
3    3
4    1
Name: category_encoded, dtype: int64


4. MODEL DEVELOPMENT

In [60]:
import tensorflow as tf
print(tf.__version__)


2.16.1


In [61]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

# Define the model
model = Sequential([
    Embedding(input_dim=100, output_dim=16, input_shape=(padded_sequences.shape[1],)),
    Flatten(),
    Dense(10, activation='relu'),
    Dense(5, activation='softmax')  # Assuming we have 5 categories
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Summary of the model
model.summary()



/Users/hks/Library/Python/3.9/lib/python/site-packages/keras/src/layers/core/embedding.py:81: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 10, 16)         │         1,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 160)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 10)             │         1,610 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │            55 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,265 (12.75 KB)

 Trainable params: 3,265 (12.75 KB)

 Non-trainable params: 0 (0.00 B)

In [62]:
print('Shapes:')
print('X_train:', X_train.shape)
print('y_train:', y_train.shape)
print('X_val:', X_val.shape)
print('y_val:', y_val.shape)


Shapes:
X_train: (4, 10)
y_train: (4,)
X_val: (1, 10)
y_val: (1,)


5. TRAINING AND EVALUATION

In [47]:
from sklearn.model_selection import train_test_split


In [63]:
# Example reshaping if necessary
padded_sequences = np.array(padded_sequences)  # Ensure it's a NumPy array
df['category_encoded'] = np.array(df['category_encoded'])  # Ensure it's a NumPy array

# Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(padded_sequences, df['category_encoded'], test_size=0.2, random_state=42)

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val))

# Evaluate the model
val_loss, val_accuracy = model.evaluate(X_val, y_val)

print(f'Validation Accuracy: {val_accuracy:.4f}')


Epoch 1/10


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 798ms/step - accuracy: 0.2500 - loss: 1.6119 - val_accuracy: 0.0000e+00 - val_loss: 1.6027
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.2500 - loss: 1.6004 - val_accuracy: 0.0000e+00 - val_loss: 1.6045
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.2500 - loss: 1.5910 - val_accuracy: 0.0000e+00 - val_loss: 1.6062
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7500 - loss: 1.5820 - val_accuracy: 0.0000e+00 - val_loss: 1.6078
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7500 - loss: 1.5738 - val_accuracy: 0.0000e+00 - val_loss: 1.6094
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 1.5679 - val_accuracy: 0.0000e+00 - val_loss: 1.6108
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 1.5618 - val_accuracy: 0.0000e+00 - val_loss: 1.6123
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 1.5555 - val_accuracy: 0.0000e+